baseurl = "https://chris-chevalier.herokuapp.com/"
title = "Chris Chevalier"
languageCode = "en-us"
# disqusShortname = "your_disqus_shortname" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10


[author]
    name = "Christopher Chevalier"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[[menu.main]]
    name = "Resume"
    identifier = "Resume"
    url = "/resume.pdf"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Site of Chris Chevalier"
    defaultKeywords = "christopher,chris,chevalier,chris chevalier"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = true

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Computer Science Student"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    # home = "about"

    # Metadata used to drive integrations.
    googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "1969f906f1280426301ca85c0cec8aad"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/chevalierc"
    bitbucket = ""
    stackOverflow = ""
    linkedin = "https://www.linkedin.com/in/christopher-chevalier/"
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    # flattr = ""  # populate with your flattr uid
